### ISSUE TITLE
[Feature Request] support display file size using KiB format

### ISSUE THREAD

**Issue by tjx666** [brunnerh/file-properties-viewer#10]
KiB is different from KB. Programer use KiB more often.
For a file 1024 bytes:

- KB: 1.024 equals to 1024 / 1000
- KiB: 1    equals to 1024 / 1024

**Comment by brunnerh** [comment]
Released in v.1.1.0.

To change the display, set:
```json
"filePropertiesViewer.sizeMode": "kibi",
```
