### ISSUE TITLE
Support non-text files too

### ISSUE THREAD

**Issue by C0rn3j** [brunnerh/file-properties-viewer#15]
![image](https://github.com/brunnerh/file-properties-viewer/assets/1641362/20df986f-f876-40d1-9fd4-074f46c2b560)

Is there a way to enable the same view for things like images without having to right click -> properties on them?

**Comment by brunnerh** [comment]
Thought this was impossible, but found an undocumented API that contains the URI for non-text files.

![image](https://github.com/brunnerh/file-properties-viewer/assets/834235/a7653640-3c4c-438f-ac73-86893baf1a0c)

Should be fixed in v.1.2.0 (ab1417409bd747593477c375ef19d9cfbb9e90eb).
