### ISSUE TITLE
Properties viewer is blank when running on a remote session

### ISSUE THREAD

**Issue by lurk26** [brunnerh/file-properties-viewer#6]
Hi, I'm trying to use this extension on a remote session. I am using the Remote - SSH extension in VS Code where my local computer is Windows and the remote is Linux. When I open the extension on a remote session the viewer is completely blank.

**Comment by brunnerh** [comment]
I cannot guarantee correct behavior in combination with extensions like this. Chances are that nothing can be done here (maybe an error could be shown instead of a blank screen).

Is the SSH extension identifier `ms-vscode-remote.remote-ssh`?

**Comment by lurk26** [comment]
Yes that is the identifier for the extension. I just wanted to see what it would take to have it work on remote or what the actual error was. Perhaps its an easy fix and that would make it really useful for remote development. I am on a Windows PC but almost all my development happens on a remote Linux host.

**Comment by brunnerh** [comment]
The problem was on the side of the `vscode-server`, which made it unnecessarily hard to track down. Well, it should be fixed now as i changed the code to work around the issue and reported it.
